# Generated by Django 3.2.15 on 2022-08-31 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bar_and_grill', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fooditem',
            options={'ordering': ['-food_type']},
        ),
    ]
