# Generated by Django 3.2.15 on 2022-08-18 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='guest_count',
            field=models.IntegerField(choices=[(1, '1 guest'), (2, '2 guests'), (3, '3 guests'), (4, '4 guests'), (5, '5 guests'), (6, '6 guests')], default=2),
        ),
    ]
