# Generated by Django 3.2.15 on 2022-08-19 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_guest_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='guest_count',
            field=models.IntegerField(choices=[(1, '1 Guest'), (2, '2 Guests'), (3, '3 Guests'), (4, '4 Guests'), (5, '5 Guests'), (6, '6 Guests')], default=2),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Awaiting confirmation', 'Awaiting Confirmation'), ('Booking Confirmed', 'Booking Confirmed'), ('Booking Rejected', 'Booking Rejected'), ('Booking Expired', 'Booking Expired')], default='awaiting confirmation', max_length=25),
        ),
        migrations.AlterField(
            model_name='table',
            name='max_seats',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
